services:
  - type: web
    name: tennis-court-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        value: sqlite:///./data/courts.db
      - key: DEBUG
        value: false 